import { test } from '@fast-check/jest'
import { describe, expect } from '@jest/globals'
import * as E from 'fp-ts/Either'
import * as D from 'io-ts/Decoder'
import * as _ from '../src/html'
import * as fc from './fc'

describe('html', () => {
  test.each([
    ['mismatched tags', '<b><i>bold italic</b> plain</i>', '<b><i>bold italic</i></b> plain'],
    ['comment', '<!-- comment -->', ''],
    ['<a>', '<a>a</a>', '<a>a</a>'],
    [
      '<a> with attributes',
      '<a href="http://example.com/" lang="en" dir="ltr" id="a" foo>a</a>',
      '<a href="http://example.com/" lang="en" dir="ltr">a</a>',
    ],
    ['<a> with a protocol-relative link', '<a href="//example.com/">a</a>', '<a>a</a>'],
    ['<a> with a HTTPS link', '<a href="https://example.com/">a</a>', '<a href="https://example.com/">a</a>'],
    ['<a> with an FTP link', '<a href="ftp://example.com/">a</a>', '<a href="ftp://example.com/">a</a>'],
    ['<a> with an email link', '<a href="mailto:hello@example.com">a</a>', '<a href="mailto:hello@example.com">a</a>'],
    ['<a> with a fragment link', '<a href="#foo">a</a>', '<a>a</a>'],
    ['<a> with a relative link', '<a href="/foo">a</a>', '<a>a</a>'],
    ['<a> with a javascript link', '<a href="javascript:alert(\'foo\')">a</a>', '<a>a</a>'],
    ['<abbr>', '<abbr>abbr</abbr>', 'abbr'],
    ['<abbr> with attributes', '<abbr lang="en" dir="ltr" id="abbr" foo>abbr</abbr>', 'abbr'],
    ['<acronym>', '<acronym>acronym</acronym>', 'acronym'],
    ['<acronym> with attributes', '<acronym lang="en" dir="ltr" id="acronym" foo>acronym</acronym>', 'acronym'],
    ['<address>', '<address>address</address>', 'address'],
    ['<address> with attributes', '<address lang="en" dir="ltr" id="address" foo>address</address>', 'address'],
    ['<applet>', '<applet>applet</applet>', 'applet'],
    ['<applet> with attributes', '<applet alt="applet" lang="en" dir="ltr" id="applet" foo>applet</applet>', 'applet'],
    ['<area>', '<area>', ''],
    ['<area> with attributes', '<area alt="area" lang="en" dir="ltr" id="area" foo>', ''],
    ['<area> with a body', '<area>area</area>', 'area'],
    ['<article>', '<article>article</article>', 'article'],
    ['<article> with attributes', '<article lang="en" dir="ltr" id="article" foo>article</article>', 'article'],
    ['<aside>', '<aside>aside</aside>', 'aside'],
    ['<aside> with attributes', '<aside lang="en" dir="ltr" id="aside" foo>aside</aside>', 'aside'],
    ['<audio>', '<audio>audio</audio>', 'audio'],
    ['<audio> with attributes', '<audio lang="en" dir="ltr" id="audio" foo>audio</audio>', 'audio'],
    ['<b>', '<b>b</b>', '<b>b</b>'],
    ['<b> with attributes', '<b lang="en" dir="ltr" id="b" foo>b</b>', '<b lang="en" dir="ltr">b</b>'],
    ['<base>', '<base>', ''],
    ['<base> with attributes', '<base lang="en" dir="ltr" id="base" foo>', ''],
    ['<base> with a body', '<base>base</base>', 'base'],
    ['<basefont>', '<basefont>basefont</basefont>', 'basefont'],
    ['<basefont> with attributes', '<basefont lang="en" dir="ltr" id="basefont" foo>basefont</basefont>', 'basefont'],
    ['<bdi>', '<bdi>bdi</bdi>', 'bdi'],
    ['<bdi> with attributes', '<bdi lang="en" dir="ltr" id="bdi" foo>bdi</bdi>', 'bdi'],
    ['<bdo>', '<bdo>bdo</bdo>', 'bdo'],
    ['<bdo> with attributes', '<bdo lang="en" dir="ltr" id="bdo" foo>bdo</bdo>', 'bdo'],
    ['<big>', '<big>big</big>', 'big'],
    ['<big> with attributes', '<big lang="en" dir="ltr" id="big" foo>big</big>', 'big'],
    ['<blockquote>', '<blockquote>blockquote</blockquote>', 'blockquote'],
    [
      '<blockquote> with attributes',
      '<blockquote lang="en" dir="ltr" id="blockquote" foo>blockquote</blockquote>',
      'blockquote',
    ],
    ['<body>', '<body>body</body>', 'body'],
    ['<body> with attributes', '<body lang="en" dir="ltr" id="body" foo>body</body>', 'body'],
    ['<br>', '<br>', ''],
    ['<br> with attributes', '<br lang="en" dir="ltr" id="br" foo>', ''],
    ['<br> with a body', '<br>br</br>', 'br'],
    ['<button>', '<button>button</button>', 'button'],
    ['<button> with attributes', '<button lang="en" dir="ltr" id="button" foo>button</button>', 'button'],
    ['<canvas>', '<canvas>canvas</canvas>', 'canvas'],
    ['<canvas> with attributes', '<canvas lang="en" dir="ltr" id="canvas" foo>canvas</canvas>', 'canvas'],
    ['<caption>', '<caption>caption</caption>', 'caption'],
    ['<caption> with attributes', '<caption lang="en" dir="ltr" id="caption" foo>caption</caption>', 'caption'],
    ['<center>', '<center>center</center>', 'center'],
    ['<center> with attributes', '<center lang="en" dir="ltr" id="center" foo>center</center>', 'center'],
    ['<cite>', '<cite>cite</cite>', 'cite'],
    ['<cite> with attributes', '<cite lang="en" dir="ltr" id="cite" foo>cite</cite>', 'cite'],
    ['<code>', '<code>code</code>', 'code'],
    ['<code> with attributes', '<code lang="en" dir="ltr" id="code" foo>code</code>', 'code'],
    ['<col>', '<col>', ''],
    ['<col> with attributes', '<col lang="en" dir="ltr" id="col" foo>', ''],
    ['<col> with a body', '<col>col</col>', 'col'],
    ['<colgroup>', '<colgroup>colgroup</colgroup>', 'colgroup'],
    ['<colgroup> with attributes', '<colgroup lang="en" dir="ltr" id="colgroup" foo>colgroup</colgroup>', 'colgroup'],
    ['<data>', '<data>data</data>', 'data'],
    ['<data> with attributes', '<data value="data" lang="en" dir="ltr" id="data" foo>data</data>', 'data'],
    ['<datalist>', '<datalist>datalist</datalist>', 'datalist'],
    ['<datalist> with attributes', '<datalist lang="en" dir="ltr" id="datalist" foo>datalist</datalist>', 'datalist'],
    ['<dd>', '<dd>dd</dd>', 'dd'],
    ['<dd> with attributes', '<dd lang="en" dir="ltr" id="dd" foo>dd</dd>', 'dd'],
    ['<del>', '<del>del</del>', 'del'],
    ['<del> with attributes', '<del lang="en" dir="ltr" id="del" foo>del</del>', 'del'],
    ['<details>', '<details>details</details>', 'details'],
    ['<details> with attributes', '<details lang="en" dir="ltr" id="details" foo>details</details>', 'details'],
    ['<dfn>', '<dfn>dfn</dfn>', 'dfn'],
    ['<dfn> with attributes', '<dfn lang="en" dir="ltr" id="dfn" foo>dfn</dfn>', 'dfn'],
    ['<dialog>', '<dialog>dialog</dialog>', 'dialog'],
    ['<dialog> with attributes', '<dialog lang="en" dir="ltr" id="dialog" foo>dialog</dialog>', 'dialog'],
    ['<dir>', '<dir>dir</dir>', 'dir'],
    ['<dir> with attributes', '<dir lang="en" dir="ltr" id="dir" foo>dir</dir>', 'dir'],
    ['<div>', '<div>div</div>', 'div'],
    ['<div> with attributes', '<div lang="en" dir="ltr" id="div" foo>div</div>', 'div'],
    ['<dl>', '<dl>dl</dl>', 'dl'],
    ['<dl> with attributes', '<dl lang="en" dir="ltr" id="dl" foo>dl</dl>', 'dl'],
    ['<dt>', '<dt>dt</dt>', 'dt'],
    ['<dt> with attributes', '<dt lang="en" dir="ltr" id="dt" foo>dt</dt>', 'dt'],
    ['<em>', '<em>em</em>', '<i>em</i>'],
    ['<em> with attributes', '<em lang="en" dir="ltr" id="em" foo>em</em>', '<i lang="en" dir="ltr">em</i>'],
    ['<embed>', '<embed>', ''],
    ['<embed> with attributes', '<embed lang="en" dir="ltr" id="embed" foo>', ''],
    ['<embed> with a body', '<embed>embed</embed>', 'embed'],
    ['<fieldset>', '<fieldset>fieldset</fieldset>', 'fieldset'],
    ['<fieldset> with attributes', '<fieldset lang="en" dir="ltr" id="fieldset" foo>fieldset</fieldset>', 'fieldset'],
    ['<figcaption>', '<figcaption>figcaption</figcaption>', 'figcaption'],
    [
      '<figcaption> with attributes',
      '<figcaption lang="en" dir="ltr" id="figcaption" foo>figcaption</figcaption>',
      'figcaption',
    ],
    ['<figure>', '<figure>figure</figure>', 'figure'],
    ['<figure> with attributes', '<figure lang="en" dir="ltr" id="figure" foo>figure</figure>', 'figure'],
    ['<font>', '<font>font</font>', 'font'],
    ['<font> with attributes', '<font lang="en" dir="ltr" id="font" foo>font</font>', 'font'],
    ['<footer>', '<footer>footer</footer>', 'footer'],
    ['<footer> with attributes', '<footer lang="en" dir="ltr" id="footer" foo>footer</footer>', 'footer'],
    ['<form>', '<form>form</form>', 'form'],
    ['<form> with attributes', '<form lang="en" dir="ltr" id="form" foo>form</form>', 'form'],
    ['<frame>', '<frame>frame</frame>', 'frame'],
    ['<frame> with attributes', '<frame lang="en" dir="ltr" id="frame" foo>frame</frame>', 'frame'],
    ['<frameset>', '<frameset>frameset</frameset>', 'frameset'],
    ['<frameset> with attributes', '<frameset lang="en" dir="ltr" id="frameset" foo>frameset</frameset>', 'frameset'],
    ['<h1>', '<h1>h1</h1>', '<h1>h1</h1>'],
    ['<h1> with attributes', '<h1 lang="en" dir="ltr" id="h1" foo>h1</h1>', '<h1 lang="en" dir="ltr">h1</h1>'],
    ['<h1> with no text', '<h1> &nbsp;\n</h1>', ''],
    ['<h2>', '<h2>h2</h2>', '<h2>h2</h2>'],
    ['<h2> with attributes', '<h2 lang="en" dir="ltr" id="h2" foo>h2</h2>', '<h2 lang="en" dir="ltr">h2</h2>'],
    ['<h2> with no text', '<h2> &nbsp;\n</h2>', ''],
    ['<h3>', '<h3>h3</h3>', '<h3>h3</h3>'],
    ['<h3> with attributes', '<h3 lang="en" dir="ltr" id="h3" foo>h3</h3>', '<h3 lang="en" dir="ltr">h3</h3>'],
    ['<h3> with no text', '<h3> &nbsp;\n</h3>', ''],
    ['<h4>', '<h4>h4</h4>', 'h4'],
    ['<h4> with attributes', '<h4 lang="en" dir="ltr" id="h4" foo>h4</h4>', 'h4'],
    ['<h5>', '<h5>h5</h5>', 'h5'],
    ['<h5> with attributes', '<h5 lang="en" dir="ltr" id="h5" foo>h5</h5>', 'h5'],
    ['<h6>', '<h6>h6</h6>', 'h6'],
    ['<h6> with attributes', '<h6 lang="en" dir="ltr" id="h6" foo>h6</h6>', 'h6'],
    ['<head>', '<head>head</head>', 'head'],
    ['<head> with attributes', '<head lang="en" dir="ltr" id="head" foo>head</head>', 'head'],
    ['<header>', '<header>header</header>', 'header'],
    ['<header> with attributes', '<header lang="en" dir="ltr" id="header" foo>header</header>', 'header'],
    ['<hr>', '<hr>', ''],
    ['<hr> with attributes', '<hr>', ''],
    ['<hr> with a body', '<hr>hr</hr>', 'hr'],
    ['<html>', '<html>html</html>', 'html'],
    ['<html> with attributes', '<html lang="en" dir="ltr" id="html" foo>html</html>', 'html'],
    ['<i>', '<i>i</i>', '<i>i</i>'],
    ['<i> with attributes', '<i lang="en" dir="ltr" id="i" foo>i</i>', '<i lang="en" dir="ltr">i</i>'],
    ['<iframe>', '<iframe>iframe</iframe>', 'iframe'],
    ['<iframe> with attributes', '<iframe lang="en" dir="ltr" id="iframe" foo>iframe</iframe>', 'iframe'],
    ['<img>', '<img>', ''],
    ['<img> with attributes', '<img src="some-image.png" alt="" lang="en" dir="ltr" id="img" foo>', ''],
    ['<img> with a body', '<img>img</img>', 'img'],
    ['<input>', '<input>', ''],
    ['<input> with attributes', '<input lang="en" dir="ltr" id="input" foo>', ''],
    ['<input> with a body', '<input>input</input>', 'input'],
    ['<ins>', '<ins>ins</ins>', 'ins'],
    ['<ins> with attributes', '<ins lang="en" dir="ltr" id="ins" foo>ins</ins>', 'ins'],
    ['<kbd>', '<kbd>kbd</kbd>', 'kbd'],
    ['<kbd> with attributes', '<kbd lang="en" dir="ltr" id="kbd" foo>kbd</kbd>', 'kbd'],
    ['<label>', '<label>label</label>', 'label'],
    ['<label> with attributes', '<label lang="en" dir="ltr" id="label" foo>label</label>', 'label'],
    ['<legend>', '<legend>legend</legend>', 'legend'],
    ['<legend> with attributes', '<legend lang="en" dir="ltr" id="legend" foo>legend</legend>', 'legend'],
    ['<li>', '<li>li</li>', '<li>li</li>'],
    ['<li> with attributes', '<li lang="en" dir="ltr" id="li" foo>li</li>', '<li lang="en" dir="ltr">li</li>'],
    ['<li> with no text', '<li> &nbsp;\n</li>', ''],
    ['<link>', '<link>', ''],
    ['<link> with attributes', '<link lang="en" dir="ltr" id="link" foo>', ''],
    ['<link> with a body', '<link>link</link>', 'link'],
    ['<main>', '<main>main</main>', 'main'],
    ['<main> with attributes', '<main lang="en" dir="ltr" id="main" foo>main</main>', 'main'],
    ['<map>', '<map>map</map>', 'map'],
    ['<map> with attributes', '<map lang="en" dir="ltr" id="map" foo>map</map>', 'map'],
    ['<mark>', '<mark>mark</mark>', 'mark'],
    ['<mark> with attributes', '<mark lang="en" dir="ltr" id="mark" foo>mark</mark>', 'mark'],
    ['<meta>', '<meta>', ''],
    ['<meta> with attributes', '<meta lang="en" dir="ltr" id="meta" foo>', ''],
    ['<meta> with a body', '<meta>meta</meta>', 'meta'],
    ['<meter>', '<meter>meter</meter>', 'meter'],
    ['<meter> with attributes', '<meter value="0" lang="en" dir="ltr" id="meter" foo>meter</meter>', 'meter'],
    ['<nav>', '<nav>nav</nav>', 'nav'],
    ['<nav> with attributes', '<nav lang="en" dir="ltr" id="nav" foo>nav</nav>', 'nav'],
    ['<noframes>', '<noframes>noframes</noframes>', 'noframes'],
    ['<noframes> with attributes', '<noframes lang="en" dir="ltr" id="noframes" foo>noframes</noframes>', 'noframes'],
    ['<noscript>', '<noscript>noscript</noscript>', 'noscript'],
    ['<noscript> with attributes', '<noscript lang="en" dir="ltr" id="noscript" foo>noscript</noscript>', 'noscript'],
    ['<object>', '<object>object</object>', 'object'],
    ['<object> with attributes', '<object lang="en" dir="ltr" id="object" foo>object</object>', 'object'],
    ['<ol>', '<ol>ol</ol>', '<ol>ol</ol>'],
    ['<ol> with attributes', '<ol lang="en" dir="ltr" id="ol" foo>ol</ol>', '<ol lang="en" dir="ltr">ol</ol>'],
    ['<ol> with no text', '<ol> &nbsp;\n</ol>', ''],
    ['<optgroup>', '<optgroup>optgroup</optgroup>', 'optgroup'],
    [
      '<optgroup> with attributes',
      '<optgroup label="optgroup" lang="en" dir="ltr" id="optgroup" foo>optgroup</optgroup>',
      'optgroup',
    ],
    ['<option>', '<option>option</option>', ''],
    ['<option> with attributes', '<option lang="en" dir="ltr" id="option" foo>option</option>', ''],
    ['<output>', '<output>output</output>', 'output'],
    ['<output> with attributes', '<output lang="en" dir="ltr" id="output" foo>output</output>', 'output'],
    ['<p>', '<p>p</p>', '<p>p</p>'],
    ['<p> with attributes', '<p lang="en" dir="ltr" id="p" foo>p</p>', '<p lang="en" dir="ltr">p</p>'],
    ['<p> with no text', '<p> &nbsp;\n</p>', ''],
    ['<param>', '<param>', ''],
    ['<param> with attributes', '<param lang="en" dir="ltr" id="param" foo>', ''],
    ['<param> with a body', '<param>param</param>', 'param'],
    ['<picture>', '<picture>picture</picture>', 'picture'],
    ['<picture> with attributes', '<picture lang="en" dir="ltr" id="picture" foo>picture</picture>', 'picture'],
    ['<pre>', '<pre>pre</pre>', 'pre'],
    ['<pre> with attributes', '<pre lang="en" dir="ltr" id="pre" foo>pre</pre>', 'pre'],
    ['<progress>', '<progress>progress</progress>', 'progress'],
    ['<progress> with attributes', '<progress lang="en" dir="ltr" id="progress" foo>progress</progress>', 'progress'],
    ['<q>', '<q>q</q>', 'q'],
    ['<q> with attributes', '<q lang="en" dir="ltr" id="q" foo>q</q>', 'q'],
    ['<rp>', '<rp>rp</rp>', 'rp'],
    ['<rp> with attributes', '<rp lang="en" dir="ltr" id="rp" foo>rp</rp>', 'rp'],
    ['<rt>', '<rt>rt</rt>', 'rt'],
    ['<rt> with attributes', '<rt lang="en" dir="ltr" id="rt" foo>rt</rt>', 'rt'],
    ['<ruby>', '<ruby>ruby</ruby>', 'ruby'],
    ['<ruby> with attributes', '<ruby lang="en" dir="ltr" id="ruby" foo>ruby</ruby>', 'ruby'],
    ['<s>', '<s>s</s>', 's'],
    ['<s> with attributes', '<s lang="en" dir="ltr" id="s" foo>s</s>', 's'],
    ['<samp>', '<samp>samp</samp>', 'samp'],
    ['<samp> with attributes', '<samp lang="en" dir="ltr" id="samp" foo>samp</samp>', 'samp'],
    ['<script>', '<script>script</script>', ''],
    ['<script> with attributes', '<script lang="en" dir="ltr" id="script" foo>script</script>', ''],
    ['<section>', '<section>section</section>', 'section'],
    ['<section> with attributes', '<section lang="en" dir="ltr" id="section" foo>section</section>', 'section'],
    ['<select>', '<select>select</select>', 'select'],
    ['<select> with attributes', '<select lang="en" dir="ltr" id="select" foo>select</select>', 'select'],
    ['<small>', '<small>small</small>', 'small'],
    ['<small> with attributes', '<small lang="en" dir="ltr" id="small" foo>small</small>', 'small'],
    ['<source>', '<source>', ''],
    ['<source> with attributes', '<source lang="en" dir="ltr" id="source" foo>', ''],
    ['<source> with a body', '<source>source</source>', 'source'],
    ['<span>', '<span>span</span>', 'span'],
    ['<span> with attributes', '<span lang="en" dir="ltr" id="span" foo>span</span>', 'span'],
    ['<strike>', '<strike>strike</strike>', 'strike'],
    ['<strike> with attributes', '<strike lang="en" dir="ltr" id="strike" foo>strike</strike>', 'strike'],
    ['<strong>', '<strong>strong</strong>', '<b>strong</b>'],
    [
      '<strong> with attributes',
      '<strong lang="en" dir="ltr" id="strong" foo>strong</strong>',
      '<b lang="en" dir="ltr">strong</b>',
    ],
    ['<style>', '<style>style</style>', ''],
    ['<style> with attributes', '<style lang="en" dir="ltr" id="style" foo>style</style>', ''],
    ['<sub>', '<sub>sub</sub>', '<sub>sub</sub>'],
    ['<sub> with attributes', '<sub lang="en" dir="ltr" id="sub" foo>sub</sub>', '<sub lang="en" dir="ltr">sub</sub>'],
    ['<summary>', '<summary>summary</summary>', 'summary'],
    ['<summary> with attributes', '<summary lang="en" dir="ltr" id="summary" foo>summary</summary>', 'summary'],
    ['<sup>', '<sup>sup</sup>', '<sup>sup</sup>'],
    ['<sup> with attributes', '<sup lang="en" dir="ltr" id="sup" foo>sup</sup>', '<sup lang="en" dir="ltr">sup</sup>'],
    ['<svg>', '<svg>svg</svg>', 'svg'],
    ['<svg> with attributes', '<svg lang="en" dir="ltr" id="svg" foo>svg</svg>', 'svg'],
    ['<table>', '<table>table</table>', 'table'],
    ['<table> with attributes', '<table lang="en" dir="ltr" id="table" foo>table</table>', 'table'],
    ['<tbody>', '<tbody>tbody</tbody>', 'tbody'],
    ['<tbody> with attributes', '<tbody lang="en" dir="ltr" id="tbody" foo>tbody</tbody>', 'tbody'],
    ['<td>', '<td>td</td>', 'td'],
    ['<td> with attributes', '<td lang="en" dir="ltr" id="td" foo>td</td>', 'td'],
    ['<template>', '<template>template</template>', 'template'],
    ['<template> with attributes', '<template lang="en" dir="ltr" id="template" foo>template</template>', 'template'],
    ['<textarea>', '<textarea>textarea</textarea>', ''],
    ['<textarea> with attributes', '<textarea lang="en" dir="ltr" id="textarea" foo>textarea</textarea>', ''],
    ['<tfoot>', '<tfoot>tfoot</tfoot>', 'tfoot'],
    ['<tfoot> with attributes', '<tfoot lang="en" dir="ltr" id="tfoot" foo>tfoot</tfoot>', 'tfoot'],
    ['<th>', '<th>th</th>', 'th'],
    ['<th> with attributes', '<th lang="en" dir="ltr" id="th" foo>th</th>', 'th'],
    ['<thead>', '<thead>thead</thead>', 'thead'],
    ['<thead> with attributes', '<thead lang="en" dir="ltr" id="thead" foo>thead</thead>', 'thead'],
    ['<time>', '<time>time</time>', 'time'],
    ['<time> with attributes', '<time lang="en" dir="ltr" id="time" foo>time</time>', 'time'],
    ['<title>', '<title>title</title>', 'title'],
    ['<title> with attributes', '<title lang="en" dir="ltr" id="title" foo>title</title>', 'title'],
    ['<tr>', '<tr>tr</tr>', 'tr'],
    ['<tr> with attributes', '<tr lang="en" dir="ltr" id="tr" foo>tr</tr>', 'tr'],
    ['<track>', '<track>', ''],
    ['<track> with attributes', '<track src="#" lang="en" dir="ltr" id="track" foo>', ''],
    ['<track> with a body', '<track>track</track>', 'track'],
    ['<tt>', '<tt>tt</tt>', 'tt'],
    ['<tt> with attributes', '<tt lang="en" dir="ltr" id="tt" foo>tt</tt>', 'tt'],
    ['<u>', '<u>u</u>', 'u'],
    ['<u> with attributes', '<u lang="en" dir="ltr" id="u" foo>u</u>', 'u'],
    ['<ul>', '<ul>ul</ul>', '<ul>ul</ul>'],
    ['<ul> with attributes', '<ul lang="en" dir="ltr" id="ul" foo>ul</ul>', '<ul lang="en" dir="ltr">ul</ul>'],
    ['<ul> with no text', '<ul> &nbsp;\n</ul>', ''],
    ['<var>', '<var>var</var>', 'var'],
    ['<var> with attributes', '<var lang="en" dir="ltr" id="var" foo>var</var>', 'var'],
    ['<video>', '<video>video</video>', 'video'],
    ['<video> with attributes', '<video lang="en" dir="ltr" id="video" foo>video</video>', 'video'],
    ['<wbr>', '<wbr>', ''],
    ['<wbr> with attributes', '<wbr lang="en" dir="ltr" id="wbr" foo>', ''],
    ['<wbr> with a body', '<wbr>wbr</wbr>', 'wbr'],
  ])('sanitizeHtml (%s)', (_name, input, expected) => {
    const actual = _.sanitizeHtml(input)

    expect(actual.toString()).toBe(expected)
  })
})

describe('plainText', () => {
  test.each([
    ['tag', 'a b<a>c</a>d e', 'a bcd e'],
    ['tag with attributes', '<a href="http://example.com/" lang="en" dir="ltr" id="a" foo>a</a>', 'a'],
    ['mismatched tags', '<b><i>bold italic</b> plain</i>', 'bold italic plain'],
    ['comment', 'a<!-- comment -->b', 'ab'],
  ])('with a string (%s)', (_name, input, expected) => {
    const actual = _.plainText(input)

    expect(actual.toString()).toBe(expected)
  })

  test.each([
    ['tag', _.html`a b<a>c</a>d e`, 'a bcd e'],
    ['tag with attributes', _.html`<a href="http://example.com/" lang="en" dir="ltr" id="a" foo>a</a>`, 'a'],
    ['mismatched tags', _.html`<b><i>bold italic</b> plain</i`, 'bold italic plain'],
    ['comment', _.html`a<!-- comment -->b`, 'ab'],
  ])('with HTML (%s)', (_name, input, expected) => {
    const actual = _.plainText(input)

    expect(actual.toString()).toBe(expected)
  })

  test('with a template literal', () => {
    const actual = _.plainText`a b${_.html`<a>c</a>`}${[_.html`<b>d </b>`, _.html`<i> e</i>`]}${'<p>f</p>'}${[
      _.plainText`g `,
      _.plainText` h`,
    ]}${1}i j`

    expect(actual.toString()).toBe('a bcd  e&lt;p&gt;f&lt;/p&gt;g  h1i j')
  })
})

describe('RawHtmlC', () => {
  describe('decode', () => {
    test.prop([fc.string()])('with a string', string => {
      const actual = _.RawHtmlC.decode(string)

      expect(actual).toStrictEqual(D.success(_.rawHtml(string)))
    })

    test.prop([fc.html()])('with HTML', html => {
      const actual = _.RawHtmlC.decode(html)

      expect(actual).toStrictEqual(D.success(html))
    })

    test.prop([fc.anything().filter(value => typeof value !== 'string' && !(value instanceof String))])(
      'with a non-string',
      value => {
        const actual = _.RawHtmlC.decode(value)

        expect(actual).toStrictEqual(E.left(expect.anything()))
      },
    )
  })

  test.prop([fc.html()])('encode', html => {
    const actual = _.RawHtmlC.encode(html)

    expect(actual).toStrictEqual(html.toString())
  })
})
