services:
  app:
    build:
      context: .
      target: prod
    depends_on:
      - mailcatcher
      - nginx
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URI=redis://redis:6379
      - HTTP_CACHE_REDIS_URI=redis://redis-cache:6379
      - SMTP_URI=smtp://mailcatcher:1025
    ports:
      - 3000:3000
