app = "prereview"

[env]
DB_PATH = "/data/db.sqlite"
PUBLIC_URL = "https://prereview.fly.dev/"

[mounts]
source = "prereview_data"
destination = "/data"

[[services]]
internal_port = 3000
protocol = "tcp"
script_checks = []

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["http", "tls"]
port = 443
