app = "prereview"

[env]
PUBLIC_URL = "https://prereview.fly.dev/"

[[services]]
internal_port = 3000
protocol = "tcp"
script_checks = []

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["http", "tls"]
port = 443
