import { Schema } from 'effect'

export type ClubId = typeof ClubIdSchema.Type

export const ClubIdSchema = Schema.Literal(
  'asapbio-cancer-biology',
  'asapbio-cell-biology',
  'asapbio-immunology',
  'asapbio-meta-research',
  'asapbio-metabolism',
  'asapbio-microbiology',
  'asapbio-neurobiology',
  'bimsb-neuroscience',
  'biobio',
  'biomass-biocatalysis',
  'biopeers-slu',
  'biophysics-leipzig',
  'bios2',
  'bloomington-biology',
  'cara',
  'cibca',
  'elife-ambassadors',
  'emerge',
  'etymos-analytica',
  'force11',
  'hhmi-training-program',
  'iib-mar-del-plata',
  'intersectional-feminist',
  'jmir-publications',
  'kone-consult',
  'language-club',
  'marine-invertebrates',
  'mlc-research',
  'neuroden',
  'nsa-utd',
  'open-box-science',
  'open-science-community-iraqi',
  'open-science-community-uruguay',
  'oxplants',
  'padua-biomedical-sciences',
  'parasitology-infectious-diseases',
  'plant-biotechnology',
  'plant-pathology-genomics',
  'prosac',
  'review-curate-network',
  'reviewing-dental-articles-club',
  'rr-id-student-reviewer-club',
  'sfb1638',
  'sg-biofilms-microbiome',
  'snl-semantics',
  'sun-bioinformatics',
  'surrey-microbiology',
  'translate-science',
  'tsl-preprint-club',
  'zmbp-preprint-club',
)
